<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-02T19:21:29 IST" name="Default suite" finished-at="2024-02-02T19:23:55 IST" duration-ms="146242">
    <groups>
    </groups>
    <test started-at="2024-02-02T19:21:29 IST" name="Default test" finished-at="2024-02-02T19:23:55 IST" duration-ms="146242">
      <class name="strongroom.TransferinImprest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:strongroom.TransferinImprest@a38c7fe]" started-at="2024-02-02T19:21:29 IST" name="setUp" finished-at="2024-02-02T19:21:44 IST" duration-ms="14992" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="transferinImprest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:strongroom.TransferinImprest@a38c7fe]" started-at="2024-02-02T19:21:44 IST" name="transferinImprest" data-provider="getTestData" finished-at="2024-02-02T19:22:20 IST" duration-ms="36151" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[WA Nursing Home]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[(docusate + sennoside B) Soflax (AN) tablet]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
final stock is not match with Expected stock expected [4] but found [222]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
final stock is not match with Expected stock expected [4] but found [222]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at strongroom.TransferinImprest.transferinImprest(TransferinImprest.java:182)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- transferinImprest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:strongroom.TransferinImprest@a38c7fe]" started-at="2024-02-02T19:22:20 IST" name="tearDown" finished-at="2024-02-02T19:22:30 IST" duration-ms="9926" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=transferinImprest status=FAILURE method=TransferinImprest.transferinImprest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:strongroom.TransferinImprest@a38c7fe] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="transferinImprest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:strongroom.TransferinImprest@a38c7fe]" started-at="2024-02-02T19:22:30 IST" name="transferinImprest" data-provider="getTestData" finished-at="2024-02-02T19:23:04 IST" duration-ms="33955" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Facility 3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[(amoxicillin) amoxicillin 500 mg capsule]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
final stock is not match with Expected stock expected [839] but found [837]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
final stock is not match with Expected stock expected [839] but found [837]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at strongroom.TransferinImprest.transferinImprest(TransferinImprest.java:182)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- transferinImprest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:strongroom.TransferinImprest@a38c7fe]" started-at="2024-02-02T19:23:04 IST" name="tearDown" finished-at="2024-02-02T19:23:11 IST" duration-ms="6620" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=transferinImprest status=FAILURE method=TransferinImprest.transferinImprest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:strongroom.TransferinImprest@a38c7fe] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="transferinImprest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:strongroom.TransferinImprest@a38c7fe]" started-at="2024-02-02T19:23:11 IST" name="transferinImprest" data-provider="getTestData" finished-at="2024-02-02T19:23:45 IST" duration-ms="34415" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[External facility]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[(bromocriptine) bromocriptine 5 mg capsule]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
final stock is not match with Expected stock expected [267] but found [265]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
final stock is not match with Expected stock expected [267] but found [265]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at strongroom.TransferinImprest.transferinImprest(TransferinImprest.java:182)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- transferinImprest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:strongroom.TransferinImprest@a38c7fe]" started-at="2024-02-02T19:23:45 IST" name="tearDown" finished-at="2024-02-02T19:23:55 IST" duration-ms="9963" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=transferinImprest status=FAILURE method=TransferinImprest.transferinImprest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:strongroom.TransferinImprest@a38c7fe] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:strongroom.TransferinImprest@a38c7fe]" started-at="2024-02-02T19:23:55 IST" name="tearDown" finished-at="2024-02-02T19:23:55 IST" duration-ms="122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- strongroom.TransferinImprest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
